### ISSUE TITLE
Vibrate method throws error "No implementation found for method vibrate"

### ISSUE THREAD

**Issue by bwrs** [clovisnicolas/flutter_vibrate#5]
When I try to call `Vibrate.vibrate`, it throws this error:

```MissingPluginException(No implementation found for method vibrate on channel github.com/clovisnicolas/flutter_vibrate)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      Vibrate.vibrate (package:vibrate/vibrate.dart:10:39)
```

Needless to say, it does not vibrate the phone.

I am running my program on a Motorola Moto G(4). The precise code I use to call `Vibrate.vibrate` is `ListTile(title: new Text("Plugin Vibrate"), onTap: () {Vibrate.vibrate();})`, and the preamble of my `main.dart` is

```import 'package:flutter/material.dart';
import "package:flutter/services.dart";
import 'package:vibrate/vibrate.dart';
import "dart:async";
```

Thanks in advance.

**Comment by bwrs** [comment]
Never mind; changing my widget from Stateless to Stateful fixed this. Sorry for any inconvenience I may have caused.
